### ISSUE TITLE
Бесконечный цикл дней

### ISSUE THREAD

**Issue by EHOTIK911** [ntlifee/Warehouse-Automation#4]
1. Запускаем приложение.
2. Выставляем ползунок "количество дней моделирования" на 30.
3. Запускаем приложение и ждем, пока смоделируется >10 дней.
4. Затем ставим ползунок на значение: 10.
5. Программа циклится и выводит дни до бесконечности.
![image](https://github.com/ntlifee/Warehouse-Automation/assets/42716046/fbf68bf2-8966-4110-828e-0533eb33f306)
6. Ожидаемый результат: Остановка программы.

**Comment by ntlifee** [comment]
Исправлено. Добавлена блокировка кнопки и ползунков при запуске моделирования.
